### ISSUE TITLE
Examples broken?

### ISSUE THREAD

**Issue by tomjaguarpaw** [ndmitchell/hogle#1]
On http://hoogle.haskell.org/ I see the following, which I guess is not intended.

```
Example searches:
map
$query=(a -> b) -> [a] -> [b]$ $#search$
$query=Ord a => [a] -> [a]$ $#search$
$query=Data.Map.insert$ $#search$
```

**Comment by ndmitchell** [comment]
Fixed. Not intended, but not a surprise, and half those searches don't work anyway. But fixed now.
